/**
 * The exception package is used to throw an exception.
 */
package by.training.task01.exception;
